name: React CI Pipeline

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a test file
      run: |
        echo "Hello from Self-Hosted Runner" > test.txt
        cat test.txt

    - name: Show success message
      run: echo "Pipeline executed successfully on self-hosted runner"