name: React CI Pipeline

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Navigate to project folder
      run: cd react-ci-pipeline

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd react-ci-pipeline
        npm install

    - name: Build the app
      run: |
        cd react-ci-pipeline
        echo "Build completed successfully!"